- id: url:https://aclanthology.org/2025.coling-main.638
  image: ./../images/default.jpg
  date: '2025-01-25' 

- id: doi:10.48550/arXiv.2501.17557
  image: ./../images/default.jpg
  date: '2025-01-30' 




- id: doi:10.18653/v1/2024.findings-emnlp.881
  image: ./../images/default.jpg
  date: '2024-11-18' 

- id: doi:10.48550/ARXIV.2409.08963
  image: ./../images/default.jpg
  date: '2024-10-12' 

- id: doi:10.48550/ARXIV.2409.09001
  image: ./../images/default.jpg
  date: '2024-10-12' 
 
- id: doi:10.48550/ARXIV.2409.13521
  image: ./../images/default.jpg
  date: '2024-10-15' 

- id: doi:10.48550/arXiv.2407.09364
  image: ./../images/default.jpg 
  date: '2024-07-12'

- id: doi:10.1007/s10994-024-06581-4
  image: ./../images/default.jpg
  date: '2024-08-12' 

- id: doi:10.1007/s41109-024-00633-3
  image: ./../images/default.jpg
  date: '2024-07-15'

- id: doi:10.1016/j.eswa.2024.123320
  image: ./../images/default.jpg
  date: '2024-06-08' 

- id: doi:10.1145/3589334.3645646
  image: ./../images/default.jpg
  date: '2024-05-17' 

- id: doi:10.1145/3614419.3644013
  image: ./../images/default.jpg
  date: '2024-05-04' 
 

 
# arXiv 2024-2
- id: doi:10.48550/ARXIV.2401.14524
  image: ./../images/liraiEU2.jpg
  date: '2024-01-25'

# arXiv 2024-1
- id: doi:10.48550/arXiv.2401.07115
  image: ./../images/mbti.jpg 
  date: '2024-01-13'




- id: " "
  title: "Topic Similarities in Rights and Duties across European Constitutions using Transformer-based Language Models"
  authors:
    - Candida M. Greco
    - Andrea Tagarelli
  publisher: ACM Hypertext-2023 Workshop on 'Legal Information Retrieval meets Artificial Intelligence Workshop' (LIRAI) 
  date: '2023-12-01'
  link: https://ceur-ws.org/Vol-3594/paper4.pdf
  image: ./../images/liraiEU2.jpg

- id: " "
  title: "GDPR Article Retrieval based on Domain-adaptive and Task-adaptive Legal Pre-trained Language Models"
  authors:
    - Andrea Simeri
    - Andrea Tagarelli
  publisher: ACM Hypertext-2023 Workshop on 'Legal Information Retrieval meets Artificial Intelligence Workshop' (LIRAI) 
  date: '2023-12-01'
  link: https://ceur-ws.org/Vol-3594/paper5.pdf
  image: ./../images/liraiGDPR.jpg
 

- id: "  "
  title: "Exploring domain and task adaptation of LamBERTa models for article retrieval on the Italian Civil Code"
  authors:
    - Andrea Simeri
    - Andrea Tagarelli
  publisher: The 19th Conference on Information and Research science Connecting to Digital and Library science (IRCDL) 
  date: '2023-04-21'
  link: https://ceur-ws.org/Vol-3365/paper4.pdf
  image: ./../images/AIlaw.jpg



 



  # SciRep 2023
- id: doi:10.1038/s41598-023-48200-7
  image: ./../images/migration.jpg

# ARTI 2023
- id: doi:10.1007/s10506-023-09374-7
  image: ./../images/AIlaw.jpg

# DAMI 2023
- id: doi:10.1007/S10618-023-00937-5
  image: ./../images/cc4.jpg

# DiB 2023
- id: doi:10.1016/j.dib.2023.109749
  image: ./../images/nftdataset.jpg

# Under review 2023
- id: doi:10.48550/arXiv.2305.19056
  image: ./../images/migration.jpg

# ICT-DM 2023
- id: doi:10.1109/ICT-DM58371.2023.10286927
  image: ./../images/climate.jpg

# SIGIR 2023
- id: doi:10.1145/3539618.3591821
  image: ./../images/sonar.jpg

# WWW 2023
- id: doi:10.1145/3543507.3583520
  image: ./../images/merlin.jpg

# Under review 2023 - ACM Trans 2025
- id: doi:10.1145/3703411
  image: ./../images/visualinspirationnetw.jpg

# Pattern Recognition Letters 2023
- id: doi:10.1016/j.patrec.2023.02.016
  image: ./../images/health.jpg




# APNS 2022
- id: doi:10.1007/s41109-022-00504-9
  image: ./../images/comlhan.jpg

# ICPR 2022
- id: doi:10.1109/ICPR56361.2022.9956039
  image: ./../images/lal.jpg

# DS 2022
- id: doi:10.1007/978-3-031-18840-4_22
  image: ./../images/fairness.jpg

# SIGIR 2022
- id: doi:10.1145/3477495.3531668
  image: ./../images/lawnetviz.jpg
  title: LawNet-Viz - A Web-based System to Visually Explore Networks of Law Article References

# OSNEM 2022
- id: doi:10.1016/j.osnem.2022.100220
  image: ./../images/osnem22.jpg

# NLDB 2022
- id: doi:10.1007/978-3-031-08473-7_45
  image: ./../images/nldb22.jpg

# ICWSM 2022
- id: doi:10.1609/icwsm.v16i1.19391
  image: ./../images/icwsm22.jpg

# CSUV 2022
- id: doi:10.1145/3444688
  image: ./../images/mlnets6.jpg




# APNS 2021_
- id: doi:10.1007/s41109-021-00420-4
  image: ./../images/attention.jpg

# APNS 2021
- id: doi:10.1007/s41109-021-00392-5
  image: ./../images/mastodon5.jpg

# AI and Law 2021
- id: doi:10.1007/s10506-021-09301-8
  image: ./../images/lamberta.jpg

# InfSci 2021
- id: doi:10.1016/J.INS.2020.08.093
  image: ./../images/mlnets.jpg

# ECMLPKDD 2021
- id: doi:10.1007/978-3-030-86520-7_31
  image: ./../images/CCwGWB.jpg

